; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:adafruit_itsybitsy_m4]
platform = atmelsam
board = adafruit_itsybitsy_m4
framework = arduino
lib_deps = 
	adafruit/Adafruit NeoPixel@^1.12.3
	./ext/madleech-Button-v1.0.0-13-g7544d7e.zip
lib_ignore = Adafruit TinyUSB Library
